library(ape)
library(phytools)
library(RColorBrewer)
setwd("C:/Users/barabi/Desktop")
tree_319 <- read.tree("320_nodulating_bacteria.nwk")
tree_98 <- read.tree("98_nodulating_species_tree.nwk")
plot(tree_97, cex = 0.3)
data_319 <- read.csv2("Nodulation_Matrix.csv", row.names = species_319)
data_98 <- read.csv2("98_species_nodulation_matrix.csv", row.names = species_98)

species_319 <- c("Ensifer_adhaerens", "Ensifer_sojae", "Ensifer_alkalisoli", "Ensifer_aridi", "Ensifer_glycinis",
             "Phyllobacterium_sophorae", "Phyllobacterium_brassicacearum", "Phyllobacterium_salinisoli",
             "Phyllobacterium_zundukense", "Methylobacterium_currus", "Methylobacterium_gossipiicola",
             "Methylobacterium_indicum", "Methylobacterium_nodulans", "Methylobacterium_oryzae", 
             "Methylobacterium_phyllostachyos", "Methylobacterium_platani", "Methylobacterium_pseudosasicola",
             "Methylobacterium_radiotolerans", "Bosea_vaviloviae", "Microvirga_lotononidis", 
             "Microvirga_massiliensis", "Microvirga_vignae", "Burkholderia_dabaoshanensis", 
             "Burkholderia_gladioli", "Burkholderia_glumae", "Burkholderia_insecticola", 
             "Burkholderia_novacaledonica", "Burkholderia_plantarii", "Burkholderia_cepacia", 
             "Burkholderia_cenocepacia", "Burkholderia_multivorans", "Burkholderia_ambifaria", 
             "Burkholderia_dolosa", "Burkholderia_lata", "Burkholderia_vietnamiensis", "Burkholderia_pyrrocinia",
             "Burkholderia_catarinensis", "Burkholderia_puraquae", "Burkholderia_paludis", 
             "Burkholderia_metallica", "Burkholderia_stabilis", "Burkholderia_stagnalis", 
             "Burkholderia_seminalis", "Burkholderia_territorii", "Burkholderia_pseudomultivorans", 
             "Herbaspirillum_autotrophicum", "Herbaspirillum_hiltneri", "Herbaspirillum_rhizosphaerae",
             "Herbaspirillum_seropedicae", "Cupriavidus_alkaliphilus", "Cupriavidus_basilensis",
             "Cupriavidus_gilardii", "Cupriavidus_metallidurans", "Cupriavidus_necator", 
             "Cupriavidus_oxalaticus", "Cupriavidus_pauculus", "Cupriavidus_pinatubonensis", 
             "Cupriavidus_plantarum", "Cupriavidus_taiwanensis", "Klebsiella_aerogenes",
             "Dichotomicrobium_thermohalophilum", "Hyphomicrobium_facile", "Methylorubrum_populi",
             "Methylorubrum_salsuginis", "Methylorubrum_zatmanii", "Mycoplana_dimorpha",
             "Caballeronia_arationis", "Caballeronia_arvi", "Caballeronia_calidae", "Caballeronia_choica",
             "Caballeronia_concitans", "Caballeronia_cordobensis", "Caballeronia_fortuita",
             "Caballeronia_glathei", "Caballeronia_glebae", "Caballeronia_grimmiae", "Caballeronia_hypogeia",
             "Caballeronia_jiangsuensis", "Caballeronia_megalochromosomata", "Caballeronia_mineralivorans",
             "Caballeronia_pedi", "Caballeronia_peredens", "Caballeronia_ptereochthonis", 
             "Caballeronia_sordidicola", "Caballeronia_temeraria", "Caballeronia_terrestris", 
             "Caballeronia_udeis", "Caballeronia_zhejiangensis", "Pandoraea_apista", "Pandoraea_norimbergensis",
             "Pandoraea_oxalativorans", "Pandoraea_pnomenusa", "Pandoraea_pulmonicola", "Pandoraea_thiooxydans",
             "Pandoraea_vervacti", "Paraburkholderia_acidipaludis", "Paraburkholderia_aromaticivorans",
             "Paraburkholderia_aspalathi", "Paraburkholderia_bannensis", "Paraburkholderia_bryophila",
             "Paraburkholderia_caballeronis", "Paraburkholderia_caffeinilytica", "Paraburkholderia_caledonica",
             "Paraburkholderia_caribensis", "Paraburkholderia_caryophylli", "Paraburkholderia_diazotrophica",
             "Paraburkholderia_dilworthii", "Paraburkholderia_endofungorum", "Paraburkholderia_ferrariae",
             "Paraburkholderia_fungorum", "Paraburkholderia_ginsengisoli", "Paraburkholderia_ginsengiterrae",
             "Paraburkholderia_graminis", "Paraburkholderia_heleia", "Paraburkholderia_hospita", 
             "Paraburkholderia_kururiensis", "Paraburkholderia_mimosarum", "Paraburkholderia_monticola",
             "Paraburkholderia_nodosa", "Paraburkholderia_oxyphila", "Paraburkholderia_phenazinium",
             "Paraburkholderia_phenoliruptrix", "Paraburkholderia_phosphatilytica", "Paraburkholderia_phymatum",
             "Paraburkholderia_phytofirmans", "Paraburkholderia_rhizoxinica", "Paraburkholderia_rhynchosiae",
             "Paraburkholderia_ribeironis", "Paraburkholderia_sacchari", "Paraburkholderia_sartisoli",
             "Paraburkholderia_sprentiae", "Paraburkholderia_susongensis", "Paraburkholderia_symbiotica",
             "Paraburkholderia_terrae", "Paraburkholderia_terricola", "Paraburkholderia_tropica",
             "Paraburkholderia_tuberum", "Paraburkholderia_unamae", "Paucimonas_lemoignei", "Ralstonia_insidiosa",
             "Ralstonia_mannitolilytica", "Ralstonia_pickettii", "Ralstonia_solanacearum", "Robbsia_andropogonis",
             "Duganella_sacchari", "Duganella_zoogloeoides", "Glaciimonas_sp.", "Herminiimonas_arsenitoxidans",
             "Janthinobacterium_agaricidamnosum", "Janthinobacterium_lividum", "Janthinobacterium_svalbardensis",
             "Massilia_alkalitolerans", "Massilia_armeniaca", "Massilia_aurea", "Massilia_eurypsychrophila",
             "Massilia_namucuonensis", "Massilia_niastensis", "Massilia_oculi", "Massilia_phosphatilytica",
             "Massilia_psychrophila", "Massilia_putida", "Massilia_timonae", "Massilia_violaceinigra",
             "Massilia_yuzhufengensis", "Noviherbaspirillum_autotrophicum", "Noviherbaspirillum_denitrificans",
             "Noviherbaspirillum_humi", "Noviherbaspirillum_massiliense", "Pseudoduganella_violaceinigra",
             "Solimicrobium_silvestre", "Novimethylophilus_kurashikiensis", "Azotobacter_beijerinckii", 
             "Azotobacter_chroococcum", "Azotobacter_vinelandii", "Rugamonas_rubra", "Pseudomonas_acidophila",
             "Pseudomonas_jinjuensis", "Pseudomonas_mendocina", "Pseudomonas_furukawaii",
             "Pseudomonas_resinovorans", "Pseudomonas_alcaliphila", "Pseudomonas_alkylphenolica",
             "Pseudomonas_benzenivorans", "Pseudomonas_borbori", "Pseudomonas_capeferrum",
             "Pseudomonas_chengduensis", "Pseudomonas_chlororaphis", "Pseudomonas_delhiensis",
             "Pseudomonas_donghuensis", "Pseudomonas_entomophila", "Pseudomonas_flexibilis", "Pseudomonas_gingeri",
             "Pseudomonas_guariconensis", "Pseudomonas_guguanensis", "Pseudomonas_indica", "Pseudomonas_jessenii",
             "Pseudomonas_knackmussii", "Pseudomonas_kunmingensis", "Pseudomonas_linyingensis",
             "Pseudomonas_oryzae", "Pseudomonas_panipatensis", "Pseudomonas_pelagia", "Pseudomonas_denitrificans",
             "Pseudomonas_pohangensis", "Pseudomonas_mosselii", "Pseudomonas_plecoglossicida", "Pseudomonas_putida",
             "Pseudomonas_reidholzensis", "Pseudomonas_sagittaria", "Pseudomonas_salegens",
             "Pseudomonas_sihuiensis", "Pseudomonas_soli", "Pseudomonas_songnenensis", "Pseudomonas_stutzeri",
             "Pseudomonas_xanthomarina", "Pseudomonas_taeanensis", "Pseudomonas_taiwanensis",
             "Pseudomonas_toyotomiensis", "Pseudomonas_vranovensis", "Pseudomonas_zhaodongensis",
             "Azorhizobium_caulinodans", "Bradyrhizobium_arachidis",
             "Bradyrhizobium_canariense", "Bradyrhizobium_diazoefficiens", "Bradyrhizobium_elkanii",
             "Bradyrhizobium_embrapense", "Bradyrhizobium_icense", "Bradyrhizobium_japonicum",
             "Bradyrhizobium_jicamae", "Bradyrhizobium_lablabi", "Bradyrhizobium_liaoningense",
             "Bradyrhizobium_manausense", "Bradyrhizobium_mercantei", "Bradyrhizobium_neotropicale",
             "Bradyrhizobium_ottawaense", "Bradyrhizobium_paxllaeri", "Bradyrhizobium_retamae",
             "Bradyrhizobium_shewense", "Bradyrhizobium_tropiciagri", "Bradyrhizobium_valentinum",
             "Bradyrhizobium_viridifuturi", "Bradyrhizobium_yuanmingense", "Mesorhizobium_alhagi",
             "Mesorhizobium_amorphae", "Mesorhizobium_australicum", "Mesorhizobium_ciceri_biovar_biserrulae",
             "Mesorhizobium_erdmanii", "Mesorhizobium_hawassense", "Mesorhizobium_helmanticense",
             "Mesorhizobium_huakuii", "Mesorhizobium_japonicum", "Mesorhizobium_kowhaii", "Mesorhizobium_loti",
             "Mesorhizobium_mediterraneum", "Mesorhizobium_metallidurans", "Mesorhizobium_muleiense",
             "Mesorhizobium_opportunistum", "Mesorhizobium_prunaredense", "Mesorhizobium_qingshengii",
             "Mesorhizobium_sanjuanii", "Mesorhizobium_soli", "Mesorhizobium_sophorae", 
             "Mesorhizobium_tamadayense", "Mesorhizobium_temperatum", "Mesorhizobium_waimense",
             "Mesorhizobium_wenxiniae", "Rhizobium_acidisoli", "Rhizobium_aegyptiacum",
             "Rhizobium_alamii", "Rhizobium_altiplani", "Rhizobium_anhuiense", "Rhizobium_bangladeshense",
             "Rhizobium_esperanzae", "Rhizobium_etli", "Rhizobium_freirei", "Rhizobium_gallicum",
             "Rhizobium_giardinii_bv._giardinii", "Rhizobium_grahamii", "Rhizobium_hidalgonense",
             "Rhizobium_jaguaris", "Rhizobium_laguerreae", "Rhizobium_leguminosarum_bv._phaseoli",
             "Rhizobium_leguminosarum_bv._trifolii", "Rhizobium_leguminosarum_bv._viciae",
             "Rhizobium_loessense", "Rhizobium_lusitanum", "Rhizobium_mesoamericanum", "Rhizobium_miluonense",
             "Rhizobium_phaseoli", "Rhizobium_pisi", "Rhizobium_sophorae", "Rhizobium_sullae",
             "Rhizobium_tibeticum", "Rhizobium_tropici", "Rhizobium_tubonense", "Rhizobium_undicola",
             "Neorhizobium_galegae", "Neorhizobium_huautlense", "Kaistia_adipata", "Kaistia_granuli",
             "Sinorhizobium_americanum", "Sinorhizobium_arboris", "Sinorhizobium_fredii", "Sinorhizobium_medicae",
             "Sinorhizobium_meliloti", "Sinorhizobium_saheli", "Chelativorans_sp.", "Hoeflea_marina",
             "Hoeflea_olei", "Pseudaminobacter_salicylatoxidans", "Afipia_felis", "Afipia_massiliensis",
             "Nitrobacter_hamburgensis", "Nitrobacter_vulgaris", "Tardiphaga_robiniae", "Variibacter_gotjawalensis",
             "Pseudoxanthobacter_soli", "Xanthobacter_autotrophicus")
species_98 <- c("Ensifer_sojae", "Ensifer_alkalisoli", "Ensifer_aridi", "Ensifer_glycinis", 
                "Microvirga_lotononidis", "Microvirga_vignae", "Cupriavidus_taiwanensis", 
                "Paraburkholderia_diazotrophica", "Paraburkholderia_mimosarum", "Paraburkholderia_nodosa",
                "Paraburkholderia_phenoliruptrix", "Paraburkholderia_phymatum", "Paraburkholderia_rhynchosiae",
                "Paraburkholderia_ribeironis", "Paraburkholderia_sprentiae", "Paraburkholderia_symbiotica",
                "Paraburkholderia_terricola", "Paraburkholderia_tuberum", "Azorhizobium_caulinodans",
                "Azorhizobium_doebereinerae", "Bradyrhizobium_arachidis", "Bradyrhizobium_canariense",
                "Bradyrhizobium_diazoefficiens", "Bradyrhizobium_elkanii", "Bradyrhizobium_embrapense",
                "Bradyrhizobium_icense", "Bradyrhizobium_japonicum", "Bradyrhizobium_jicamae",
                "Bradyrhizobium_lablabi", "Bradyrhizobium_liaoningense", "Bradyrhizobium_manausense",
                "Bradyrhizobium_neotropicale", "Bradyrhizobium_ottawaense", "Bradyrhizobium_paxllaeri",
                "Bradyrhizobium_retamae", "Bradyrhizobium_shewense", "Bradyrhizobium_tropiciagri",
                "Bradyrhizobium_valentinum", "Bradyrhizobium_viridifuturi", "Bradyrhizobium_yuanmingense",
                "Mesorhizobium_alhagi", "Mesorhizobium_amorphae", "Mesorhizobium_australicum",
                "Mesorhizobium_ciceri_biovar_biserrulae", "Mesorhizobium_erdmanii", "Mesorhizobium_hawassense",
                "Mesorhizobium_helmanticense", "Mesorhizobium_huakuii", "Mesorhizobium_japonicum", 
                "Mesorhizobium_kowhaii", "Mesorhizobium_loti", "Mesorhizobium_mediterraneum",
                "Mesorhizobium_metallidurans", "Mesorhizobium_muleiense", "Mesorhizobium_opportunistum", 
                "Mesorhizobium_prunaredense", "Mesorhizobium_qingshengii", "Mesorhizobium_sanjuanii", 
                "Mesorhizobium_sophorae", "Mesorhizobium_tamadayense", "Mesorhizobium_temperatum",
                "Mesorhizobium_waimense", "Mesorhizobium_wenxiniae", "Rhizobium_acidisoli", 
                "Rhizobium_aegyptiacum", "Rhizobium_altiplani", "Rhizobium_anhuiense", "Rhizobium_bangladeshense",
                "Rhizobium_esperanzae", "Rhizobium_etli", "Rhizobium_freirei", "Rhizobium_gallicum",
                "Rhizobium_giardinii_bv._giardinii", "Rhizobium_grahamii", "Rhizobium_hidalgonense",
                "Rhizobium_jaguaris", "Rhizobium_laguerreae", "Rhizobium_leguminosarum_bv._phaseoli",
                "Rhizobium_leguminosarum_bv._trifolii", "Rhizobium_leguminosarum_bv._viciae",
                "Rhizobium_lusitanum", "Rhizobium_mesoamericanum", "Rhizobium_phaseoli", "Rhizobium_pisi",
                "Rhizobium_sophorae", "Rhizobium_sullae", "Rhizobium_tibeticum", "Rhizobium_tropici",
                "Rhizobium_undicola", "Neorhizobium_galegae", "Neorhizobium_huautlense", "Sinorhizobium_americanum",
                "Sinorhizobium_arboris", "Sinorhizobium_fredii", "Sinorhizobium_medicae", "Sinorhizobium_meliloti",
                "Sinorhizobium_saheli", "Methylobacterium_nodulans")
data1 <- as.matrix(data)
data_98 <- as.matrix(data_98)
colfunc <- colorRampPalette(c("lemonchiffon", "red"))
phylo.heatmap(tree, data_98, col = colfunc(5), fsize = 0.1)
tree_98 <- drop.tip(tree_98, "Azorhizobium_doebereinerae")
phylo.heatmap(tree_98, col = colfunc(5), data_98, fsize = 0.5)
