library(ape)
library(phytools)
setwd("C:/Users/barabi/Desktop/Ancestral_State_Reconstruction")
tree <- read.tree("proteobacteria.nwk")
is.rooted(tree)
tips <- c("Rhodopseudomonas_pentothenatexigens", "Brucella_neotomae", "Brucella_suis", "Brucella_canis", "Brucella_ovis",
          "Brucella_microti", "Brucella_ceti", "Brucella_pinnipedialis", "Brucella_abortus", 
          "Ochrobactrum_thiophenivorans", "Mesorhizobium_jarvisii", "Mesorhizobium_delmotii", "Pararhizobium_polonicum",
          "Ensifer_shofinae", "Agrobacterium_albertimagni", "Rhizobium_naphthalenivorans", "Pseudorhizobium_pelagicum",
          "Rhizobium_favelukesii", "Rhizobium_sophoriradicis", "Rhizobium_aethiopicum", "Methylovorus_sp.",
          "Ralstonia_pseudosolanacearum", "Cupriavidus_nantongensis", "Pandoraea_sputorum", "Burkholderia_ubonensis",
          "Burkholderia_diffusa", "burkholderia_anthina", "Burkholderia_reimsis", "Burkholderia_contaminans",
          "Caballeronia_telluris", "Caballeronia_catudaia", "Caballeronia_turbans", "Paraburkholderia_silvatlantica",
          "Paraburkholderia_piptadeniae", "Paraburkholderia_megapolitana", "Paraburkholderia_sediminicola", 
          "Paraburkholderia_xenovorans", "Paraburkholderia_insulsa", "Kosakonia_radicincitans", "Lelliottia_jeotgali",
          "Enterobacter_mori", "Enterobacter_chuandaensis", "Lelliottia_nimipressuralis", "Enterobacter_chengduensis",
          "Raoultella_ornithinolytica", "Klebsiella_oxytoca", "Citrobacter_werkmanii", "Citrobacter_braakii", 
          "Citrobacter_amalonaticus", "Shigella_boydii", "Pseudomonas_abyssi", "Pseudomonas_bauzanensis", 
          "Pseudomonas_zeshuii", "Pseudomonas_aeruginosa", "Pseudomonas_psychrotolerans", "Pseudomonas_kuykendallii",
          "Pseudomonas_straminea", "Pseudomonas_wadenswilerensis", "Pseudomonas_monteilii", "Pseudomonas_coleopterorum",
          "Pseudomonas_avellanae", "Pseudomonas_coronafaciens", "Pseudomonas_caricapapayae", "Pseudomonas_ficuserectae",
          "Pseudomonas_fuscovaginae", "Pseudomonas_kilonensis", "Pseudomonas_moraviensis", "Pseudomonas_mohnii", 
          "Pseudomonas_veronii", "Pseudomonas_paralactis", "Pseudomonas_salomonii", "Pseudomonas_azotoformans", 
          "Rhodomicrobium_vannielii", "Microvirga_guangxiensis", "Microvirga_ossetica", "Methylobacterium_tarhaniae", 
          "Methylobacterium_aquaticum", "Methylorubrum_extorquens", "Methylobacterium_phyllosphaerae", 
          "Methylobacterium_organophilum", "Ancylobacter_rudongensis", "Afipia_birgiae", "Bradyrhizobium_erythrophlei",
          "Bradyrhizobium_algeriense", "Bradyrhizobium_pachyrhizi", "Bradyrhizobium_stylosanthis", 
          "Devosia_epidermidihirudinis", "Paramesorhizobium_deserti", "Ochrobactrum_pseudogrignonense", 
          "Ochrobactrum_anthropi", "Brucella_inopinata", "Mesorhizobium_ephedrae", "Mesorhizobium_plurifarium", 
          "Rhizobium_subbaraonis", "Agrobacterium_arsenijevicii", "Rhizobium_leucaenae", "Rhizobium_hainanense", 
          "Rhizobium_mongolense", "Rhizobium_ecuadorense", "Methylophilus_methylotrophus", "Duganella_phyllosphaerae",
          "Herbaspirillum_aquaticum", "Herminiimonas_fonticola", "Pandoraea_faecigallinarum", "Burkholderia_latens", 
          "Paraburkholderia_soli", "Caballeronia_humi", "Paraburkholderia_eburnea", "Franconibacter_pulveris", 
          "Cronobacter_muytjensii", "Cronobacter_malonaticus", "Kosakonia_pseudosacchari", "Enterobacter_cloacae", 
          "Klebsiella_quasipneumoniae", "Kluyvera_georgiana", "Citrobacter_sedlakii", "Pseudomonas_aestusnigri", 
          "Pseudomonas_citronellolis", "Pseudomonas_anguilliseptica", "Pseudomonas_hunanensis", 
          "Pseudomonas_syringae_pv._coryli", "Pseudomonas_umsongensis", "Pseudomonas_proteolytica", 
          "Pseudomonas_palleroniana", "Klebsiella_quasivariicola", "Pseudomonas_brassicacearum")
tree_dropped <- drop.tip(tree, tip = tips)
tree_dropped$tip.label <- gsub("_", " ", tree_dropped$tip.label)
tree_dropped <- unroot(tree_dropped)
is.rooted(tree_dropped)
root <- c("Acidobacterium capsulatum", "Pyrinomonas methylalipathogenes", "Bryobacter aggregatus", 
          "Acidipila dinghuensis", "Bryocella elongata", "Edaphobacter dinghuensis", "Silvibacterium bohemicum", 
          "Terracidiphilus gabretensis", "Terriglobus roseus")
tree_rooted <- reroot(tree_dropped, node = 1163)
is.rooted(tree_rooted)
node <- fastMRCA(tree_dropped, "Pyrinomonas methylalipathogenes", "Acidipila dinghuensis")
node


# uploading the data
data <- read.csv2("ASR_data.csv")
nod_nif_stat <- data$Status
names(nod_nif_stat) <- data$Taxa
tree_rooted$edge.length[tree_rooted$edge.length == 0] <- 1e-8
dis.as <- ace(nod_nif_stat, tree_rooted, model = "ER", type = "discrete")
ulttree <- chronopl(tree_rooted, 0)
# plotting the data

mtree <- make.simmap(ulttree, nod_nif_stat, model = "ER")
cols <- setNames(c("blue", "red", "yellow"), sort(unique(nod_nif_stat)))
plotSimmap(mtree, cols, pts = FALSE, type = "fan", lwd = 0.5, fsize = 0.2)
add.simmap.legend(colors = cols, vertical = TRUE, c("Non-symbiotic nor nitrogen-fixer", "free-living nitrogen-fixers",
                                                    "Symbiotic nitrogen-fixers"))



fitER <- rerootingMethod(tree_dropped, nod_nif_stat, model = "ER")
mtree <- ladderize(mtree)
plotTree(mtree, setEnv = TRUE, offset = 0.5, type = "fan", lwd = 0.5, fsize = 0.2)
nodelabels(node = as.numeric(rownames(fitER$marginal.anc)), pie = fitER$marginal.anc, 
           piecol = c("blue", "red", "yellow"), cex = 0.1)
tiplabels(pie = to.matrix(nod_nif_stat, sort(unique(nod_nif_stat))), piecol = c("blue", "red", "yellow"), 
          cex = 0.01)
tiplabels(text = c(none, nif, nod), col = c("blue", "red", "yellow"))


none <- c("Klebsiella_aerogenes","Trabulsiella_odontotermitis"
         ,"Trabulsiella_guamensis"
         ,"Yokenella_regensburgei"
         ,"Superficieibacter_electus"
         ,"Citrobacter_farmeri"
         ,"Citrobacter_rodentium"
         ,"Citrobacter_koseri"
         ,"Salmonella_enterica"
         ,"Salmonella_bongori"
         ,"Escherichia_marmotae"
         ,"Escherichia_albertii"
         ,"Escherichia_fergusonii"
         ,"Shigella_dysenteriae"
         ,"Shigella_flexneri"
         ,"Escherichia_coli"
         ,"Citrobacter_pasteurii"
         ,"Citrobacter_freundii"
         ,"Citrobacter_youngae"
         ,"Citrobacter_europaeus"
         ,"Citrobacter_portucalensis"
         ,"Citrobacter_gillenii"
         ,"Pseudocitrobacter_faecalis"
         ,"Kluyvera_ascorbata"
         ,"Kluyvera_cryocrescens"
         ,"Enterobacter_timonensis"
         ,"Leclercia_adecarboxylata"
         ,"Enterobacter_soli"
         ,"Enterobacter_cancerogenus"
         ,"Enterobacter_hormaechei_subsp._steigerwaltii"
         ,"Enterobacter_sichuanensis"
         ,"Enterobacter_roggenkampii"
         ,"Enterobacter_asburiae"
         ,"Enterobacter_kobei"
         ,"Enterobacter_bugandensis"
         ,"Enterobacter_ludwigii"
         ,"Enterobacter_huaxiensis"
         ,"Enterobacter_tabaci"
         ,"Lelliottia_amnigena"
         ,"Lelliottia_aquatilis"
         ,"Kluyvera_intermedia"
         ,"Kosakonia_cowanii"
         ,"Siccibacter_colletis"
         ,"Siccibacter_turicensis"
         ,"Franconibacter_helveticus"
         ,"Cronobacter_condimenti"
         ,"Cronobacter_dublinensis"
         ,"Cronobacter_sakazakii"
         ,"Cronobacter_universalis"
         ,"Cronobacter_turicensis"
         ,"Rosenbergiella_nectarea"
         ,"Izhakiella_australiensis"
         ,"Izhakiella_capsodis"
         ,"Gibbsiella_quercinecans"
         ,"Limnobaculum_parvum"
         ,"Pseudomonas_sabulinigri"
         ,"Pseudomonas_oceani"
         ,"Pseudomonas_gallaeciensis"
         ,"Pseudomonas_pachastrellae"
         ,"Pseudomonas_pelagia"
         ,"Pseudomonas_xinjiangensis"
         ,"Pseudomonas_litoralis"
         ,"Pseudomonas_saudimassiliensis"
         ,"Pseudomonas_formosensis"
         ,"Pseudomonas_salegens"
         ,"Pseudomonas_yangmingensis"
         ,"Pseudomonas_luteola"
         ,"Pseudomonas_oryzihabitans"
         ,"Pseudomonas_nitroreducens"
         ,"Pseudomonas_panipatensis"
         ,"Pseudomonas_knackmussii"
         ,"Pseudomonas_delhiensis"
         ,"Pseudomonas_jinjuensis"
         ,"Pseudomonas_denitrificans"
         ,"Pseudomonas_flexibilis"
         ,"Pseudomonas_thermotolerans"
         ,"Pseudomonas_guangdongensis"
         ,"Pseudomonas_mendocina"
         ,"Pseudomonas_guguanensis"
         ,"Pseudomonas_toyotomiensis"
         ,"Pseudomonas_alcaliphila"
         ,"Pseudomonas_sihuiensis"
         ,"Pseudomonas_chengduensis"
         ,"Pseudomonas_pseudoalcaligenes"
         ,"Pseudomonas_oleovorans"
         ,"Pseudomonas_indoloxydans"
         ,"Pseudomonas_composti"
         ,"Pseudomonas_fluvialis"
         ,"Pseudomonas_alcaligenes"
         ,"Pseudomonas_pohangensis"
         ,"Pseudomonas_massiliensis"
         ,"Pseudomonas_reidholzensis"
         ,"Pseudomonas_parafulva"
         ,"Pseudomonas_cremoricolorata"
         ,"Pseudomonas_capeferrum"
         ,"Pseudomonas_putida"
         ,"Pseudomonas_plecoglossicida"
         ,"Pseudomonas_taiwanensis"
         ,"Pseudomonas_guariconensis"
         ,"Pseudomonas_entomophila"
         ,"Pseudomonas_mosselii"
         ,"Pseudomonas_soli"
         ,"Pseudomonas_japonica"
         ,"Pseudomonas_donghuensis"
         ,"Pseudomonas_alkylphenolica"
         ,"Pseudomonas_vranovensis"
         ,"Pseudomonas_rhizosphaerae"
         ,"Pseudomonas_asplenii"
         ,"Pseudomonas_agarici"
         ,"Pseudomonas_gingeri"
         ,"Pseudomonas_batumici"
         ,"Pseudomonas_chlororaphis"
         ,"Pseudomonas_protegens"
         ,"Pseudomonas_saponiphila"
         ,"Pseudomonas_corrugata"
         ,"Pseudomonas_mediterranea"
         ,"Pseudomonas_thivervalensis"
         ,"Pseudomonas_fluorescens"
         ,"Pseudomonas_kribbensis"
         ,"Pseudomonas_baetica"
         ,"Pseudomonas_granadensis"
         ,"Pseudomonas_koreensis"
         ,"Pseudomonas_frederiksbergensis"
         ,"Pseudomonas_lini"
         ,"Pseudomonas_silesiensis"
         ,"Pseudomonas_prosekii"
         ,"Pseudomonas_mandelii"
         ,"Pseudomonas_arsenicoxydans"
         ,"Pseudomonas_migulae"
         ,"Pseudomonas_moorei"
         ,"Pseudomonas_reinekei"
         ,"Pseudomonas_jessenii"
         ,"Pseudomonas_laurylsulfatovorans"
         ,"Pseudomonas_vancouverensis"
         ,"Pseudomonas_endophytica"
         ,"Pseudomonas_helleri"
         ,"Pseudomonas_lundensis"
         ,"Pseudomonas_weihenstephanensis"
         ,"Pseudomonas_taetrolens"
         ,"Pseudomonas_versuta"
         ,"Pseudomonas_fragi"
         ,"Pseudomonas_deceptionensis"
         ,"Pseudomonas_psychrophila"
         ,"Pseudomonas_yamanorum"
         ,"Pseudomonas_gessardii"
         ,"Pseudomonas_brenneri"
         ,"Pseudomonas_mucidolens"
         ,"Pseudomonas_grimontii"
         ,"Pseudomonas_tolaasii"
         ,"Pseudomonas_costantinii"
         ,"Pseudomonas_antarctica"
         ,"Pseudomonas_cedrina"
         ,"Pseudomonas_trivialis"
         ,"Pseudomonas_marginalis"
         ,"Pseudomonas_lurida"
         ,"Pseudomonas_simiae"
         ,"Pseudomonas_canadensis"
         ,"Pseudomonas_extremorientalis"
         ,"Pseudomonas_poae"
         ,"Pseudomonas_orientalis"
         ,"Pseudomonas_lactis"
         ,"Pseudomonas_synxantha"
         ,"Pseudomonas_libanensis"
         ,"Pseudomonas_rhodesiae"
         ,"Pseudomonas_extremaustralis"
         ,"Pseudomonas_panacis"
         ,"Pseudomonas_bohemica"
         ,"Pseudomonas_abietaniphila"
         ,"Pseudomonas_graminis"
         ,"Pseudomonas_lutea"
         ,"Paucimonas_lemoignei"
         ,"Pseudomonas_caspiana"
         ,"Pseudomonas_cichorii"
         ,"Pseudomonas_floridensis"
         ,"Pseudomonas_asturiensis"
         ,"Pseudomonas_viridiflava"
         ,"Pseudomonas_cannabina"
         ,"Pseudomonas_tremae"
         ,"Pseudomonas_syringae_pv._tomato"
         ,"Pseudomonas_cerasi"
         ,"Pseudomonas_syringae_pv._syringae"
         ,"Pseudomonas_congelans"
         ,"Pseudomonas_syringae_pv._tagetis"
         ,"Pseudomonas_savastanoi"
         ,"Pseudomonas_meliae"
         ,"Pseudomonas_amygdali"
         ,"Pseudomonas_seleniipraecipitans"
         ,"Pseudomonas_flavescens"
         ,"Pseudomonas_fulva"
         ,"Pseudomonas_argentinensis"
         ,"Pseudomonas_punonensis"
         ,"Pseudomonas_guineae"
         ,"Pseudomonas_peli"
         ,"Pseudomonas_cuatrocienegasensis"
         ,"Pseudomonas_taeanensis"
         ,"Pseudomonas_segetis"
         ,"Pseudomonas_marincola"
         ,"Pseudomonas_borbori"
         ,"Pseudomonas_balearica"
         ,"Pseudomonas_saudiphocaensis"
         ,"Pseudomonas_zhaodongensis"
         ,"Pseudomonas_xanthomarina"
         ,"Pseudomonas_kunmingensis"
         ,"Pseudomonas_chloritidismutans"
         ,"Pseudomonas_songnenensis"
         ,"Pseudomonas_stutzeri"
         ,"Pseudomonas_indica"
         ,"Pseudomonas_furukawaii"
         ,"Pseudomonas_resinovorans"
         ,"Pseudomonas_otitidis"
         ,"Pseudomonas_hussainii"
         ,"Pseudomonas_caeni"
         ,"Oblitimonas_alkaliphila"
         ,"Thiopseudomonas_denitrificans"
         ,"Dichotomicrobium_thermohalophilum"
         ,"Filomicrobium_insigne"
         ,"Hyphomicrobium_sulfonivorans"
         ,"Hyphomicrobium_zavarzinii"
         ,"Hyphomicrobium_nitrativorans"
         ,"Hyphomicrobium_facile"
         ,"Hyphomicrobium_denitrificans"
         ,"Nitratireductor_basaltis"
         ,"Pararhizobium_haloflavum"
         ,"Hoeflea_olei"
         ,"Hoeflea_halophila"
         ,"Hoeflea_phototrophica"
         ,"Hoeflea_marina"
         ,"Rhizobium_alamii"
         ,"Rhizobium_loessense"
         ,"Rhizobium_tubonense"
         ,"Rhizobium_tumorigenes"
         ,"Agrobacterium_tumefaciens"
         ,"Rhizobium_miluonense"
         ,"Rhizobium_multihospitium"
         ,"Rhizobium_album"
         ,"Rhizobium_taibaishanense"
         ,"Agrobacterium_vitis"
         ,"Rhizobium_oryziradicis"
         ,"Rhizobium_wuzhouense"
         ,"Agrobacterium_larrymoorei"
         ,"Agrobacterium_bohemicum"
         ,"Agrobacterium_rosae"
         ,"Agrobacterium_rubi"
         ,"Rhizobium_nepotum"
         ,"Bradyrhizobium_lupini"
         ,"Rhizobium_pusense"
         ,"Agrobacterium_rhizogenes"
         ,"Agrobacterium_deltaense"
         ,"Agrobacterium_salinitolerans"
         ,"Rhizobium_marinum"
         ,"Rhizobium_flavum"
         ,"Rhizobium_vignae"
         ,"Neorhizobium_tomejilense"
         ,"Neorhizobium_alkalisoli"
         ,"Shinella_zoogloeoides"
         ,"Mycoplana_dimorpha"
         ,"Rhizobium_oryzae"
         ,"Rhizobium_rhizosphaerae"
         ,"Rhizobium_arenae"
         ,"Pararhizobium_antarcticum"
         ,"Ensifer_adhaerens"
         ,"Phyllobacterium_myrsinacearum"
         ,"Phyllobacterium_brassicacearum"
         ,"Phyllobacterium_zundukense"
         ,"Phyllobacterium_sophorae"
         ,"Phyllobacterium_bourgognense"
         ,"Phyllobacterium_endophyticum"
         ,"Falsochrobactrum_ovis"
         ,"Ochrobactrum_grignonense"
         ,"Ochrobactrum_rhizosphaerae"
         ,"Ochrobactrum_pituitosum"
         ,"Ochrobactrum_haematophilum"
         ,"Brucella_melitensis"
         ,"Brucella_vulpis"
         ,"Ochrobactrum_intermedium"
         ,"Ochrobactrum_oryzae"
         ,"Ochrobactrum_cytisi"
         ,"Ochrobactrum_lupini"
         ,"Pseudochrobactrum_asaccharolyticum"
         ,"Phyllobacterium_leguminum"
         ,"Phyllobacterium_salinisoli"
         ,"Zhengella_mangrovi"
         ,"Chelativorans_sp."
         ,"Nitratireductor_indicus"
         ,"Nitratireductor_pacificus"
         ,"Nitratireductor_soli"
         ,"Aminobacter_aminovorans"
         ,"Pseudaminobacter_manganicus"
         ,"Aquamicrobium_defluvii"
         ,"Mesorhizobium_soli"
         ,"Pseudaminobacter_salicylatoxidans"
         ,"Aquamicrobium_aerolatum"
         ,"Aliihoeflea_sp."
         ,"Mesorhizobium_oceanicum"
         ,"Cucumibacter_marinus"
         ,"Maritalea_myrionectae"
         ,"Arsenicitalea_aurantiaca"
         ,"Devosia_enhydra"
         ,"Devosia_insulae"
         ,"Devosia_geojensis"
         ,"Devosia_limi"
         ,"Devosia_psychrophila"
         ,"Devosia_submarina"
         ,"Devosia_lucknowensis"
         ,"Devosia_elaeis"
         ,"Devosia_chinhatensis"
         ,"Devosia_crocina"
         ,"Devosia_riboflavina"
         ,"Devosia_soli"
         ,"Pelagibacterium_montanilacus"
         ,"Pelagibacterium_lentulum"
         ,"Pelagibacterium_halotolerans"
         ,"Pelagibacterium_luteolum"
         ,"Pseudoxanthobacter_soli"
         ,"Kaistia_soli"
         ,"Kaistia_algarum"
         ,"Kaistia_adipata"
         ,"Kaistia_granuli"
         ,"Bosea_lupini"
         ,"Bosea_vaviloviae"
         ,"Bosea_lathyri"
         ,"Bosea_robiniae"
         ,"Bosea_thiooxidans"
         ,"Methylobacterium_currus"
         ,"Methylobacterium_indicum"
         ,"Methylobacterium_platani"
         ,"Methylobacterium_gossipiicola"
         ,"Methylorubrum_salsuginis"
         ,"Methylorubrum_populi"
         ,"Methylorubrum_zatmanii"
         ,"Methylobacterium_phyllostachyos"
         ,"Methylobacterium_oryzae"
         ,"Methylobacterium_radiotolerans"
         ,"Methylobacterium_brachiatum"
         ,"Methylobacterium_pseudosasicola"
         ,"Microvirga_massiliensis"
         ,"Microvirga_flocculans"
         ,"Microvirga_subterranea"
         ,"Microvirga_aerophila"
         ,"Labrys_okinawensis"
         ,"Ancylobacter_aquaticus"
         ,"Starkeya_novella"
         ,"Pseudolabrys_taiwanensis"
         ,"Variibacter_gotjawalensis"
         ,"Tardiphaga_robiniae"
         ,"Oligotropha_carboxidovorans"
         ,"Afipia_felis"
         ,"Afipia_clevelandensis"
         ,"Afipia_broomeae"
         ,"Afipia_massiliensis"
         ,"Nitrobacter_hamburgensis"
         ,"Nitrobacter_vulgaris"
         ,"Nitrobacter_winogradskyi"
         ,"Neomegalonema_perideroedes"
         ,"Novimethylophilus_kurashikiensis"
         ,"Methylophilus_rhizosphaerae"
         ,"Methylotenera_versatilis"
         ,"Methylotenera_mobilis"
         ,"Methylovorus_glucosotrophus"
         ,"Methylobacillus_rhizosphaerae"
         ,"Methylobacillus_flagellatus"
         ,"Chitinimonas_taiwanensis"
         ,"Chitinimonas_koreensis"
         ,"Lautropia_mirabilis"
         ,"Noviherbaspirillum_humi"
         ,"Noviherbaspirillum_autotrophicum"
         ,"Noviherbaspirillum_denitrificans"
         ,"Noviherbaspirillum_massiliense"
         ,"Herbaspirillum_hiltneri"
         ,"Herbaspirillum_rhizosphaerae"
         ,"Herbaspirillum_autotrophicum"
         ,"Solimicrobium_silvestre"
         ,"Undibacterium_pigrum"
         ,"Undibacterium_parvum"
         ,"Oxalobacter_formigenes"
         ,"Herminiimonas_arsenitoxidans"
         ,"Herminiimonas_arsenicoxydans"
         ,"Collimonas_arenae"
         ,"Collimonas_pratensis"
         ,"Collimonas_fungivorans"
         ,"Glaciimonas_sp."
         ,"Herbaspirillum_chlorophenolicum"
         ,"Herbaspirillum_robiniae"
         ,"Herbaspirillum_huttiense_subsp._putei"
         ,"Massilia_violaceinigra"
         ,"Massilia_psychrophila"
         ,"Massilia_eurypsychrophila"
         ,"Janthinobacterium_agaricidamnosum"
         ,"Janthinobacterium_svalbardensis"
         ,"Janthinobacterium_lividum"
         ,"Rugamonas_rubra"
         ,"Duganella_sacchari"
         ,"Duganella_zoogloeoides"
         ,"Massilia_armeniaca"
         ,"Pseudoduganella_violaceinigra"
         ,"Massilia_namucuonensis"
         ,"Massilia_putida"
         ,"Massilia_phosphatilytica"
         ,"Massilia_niastensis"
         ,"Massilia_oculi"
         ,"Massilia_aurea"
         ,"Massilia_timonae"
         ,"Massilia_yuzhufengensis"
         ,"Massilia_alkalitolerans"
         ,"Hydromonas_sp."
         ,"Polynucleobacter_acidiphobus"
         ,"Polynucleobacter_difficilis"
         ,"Polynucleobacter_meluiroseus"
         ,"Polynucleobacter_sphagniphilus"
         ,"Polynucleobacter_sinensis"
         ,"Polynucleobacter_aenigmaticus"
         ,"Polynucleobacter_duraquae"
         ,"Polynucleobacter_asymbioticus"
         ,"Polynucleobacter_wuianus"
         ,"Polynucleobacter_campilacus"
         ,"Polynucleobacter_hirudinilacicola"
         ,"Polynucleobacter_yangtzensis"
         ,"Polynucleobacter_necessarius"
         ,"Polynucleobacter_victoriensis"
         ,"Polynucleobacter_cosmopolitanus"
         ,"Polynucleobacter_rarus"
         ,"Pandoraea_thiooxidans"
         ,"Pandoraea_pulmonicola"
         ,"Pandoraea_apista"
         ,"Pandoraea_vervacti"
         ,"Pandoraea_oxalativorans"
         ,"Pandoraea_pnomenusa"
         ,"Pandoraea_norimbergensis"
         ,"Paraburkholderia_rhizoxinica"
         ,"Paraburkholderia_endofungorum"
         ,"Burkholderia_stagnalis"
         ,"Burkholderia_pseudomultivorans"
         ,"Burkholderia_dolosa"
         ,"Burkholderia_multivorans"
         ,"Burkholderia_cenocepacia"
         ,"Burkholderia_seminalis"
         ,"Burkholderia_paludis"
         ,"Burkholderia_metallica"
         ,"Burkholderia_cepacia"
         ,"Burkholderia_puraquae"
         ,"Burkholderia_lata"
         ,"Burkholderia_catarinensis"
         ,"Burkholderia_pyrrocinia"
         ,"Burkholderia_stabilis"
         ,"Burkholderia_territorii"
         ,"Burkholderia_ambifaria"
         ,"Burkholderia_glumae"
         ,"Burkholderia_plantarii"
         ,"Burkholderia_gladioli"
         ,"Caballeronia_grimmiae"
         ,"Caballeronia_concitans"
         ,"Caballeronia_ptereochthonis"
         ,"Caballeronia_peredens"
         ,"Burkholderia_insecticola"
         ,"Caballeronia_jiangsuensis"
         ,"Burkholderia_novacaledonica"
         ,"Caballeronia_pedi"
         ,"Caballeronia_megalochromosomata"
         ,"Caballeronia_fortuita"
         ,"Caballeronia_temeraria"
         ,"Caballeronia_zhejiangensis"
         ,"Caballeronia_glebae"
         ,"Caballeronia_calidae"
         ,"Caballeronia_arvi"
         ,"Caballeronia_cordobensis"
         ,"Caballeronia_hypogeia"
         ,"Caballeronia_mineralivorans"
         ,"Caballeronia_udeis"
         ,"Caballeronia_sordidicola"
         ,"Caballeronia_glathei"
         ,"Caballeronia_choica"
         ,"Caballeronia_terrestris"
         ,"Caballeronia_arationis"
         ,"Paraburkholderia_acidipaludis"
         ,"Paraburkholderia_oxyphila"
         ,"Paraburkholderia_sacchari"
         ,"Paraburkholderia_phosphatilytica"
         ,"Paraburkholderia_caribensis"
         ,"Paraburkholderia_terrae"
         ,"Paraburkholderia_hospita"
         ,"Paraburkholderia_phenazinium"
         ,"Paraburkholderia_susongensis"
         ,"Paraburkholderia_monticola"
         ,"Paraburkholderia_phytofirmans"
         ,"Paraburkholderia_ginsengiterrae"
         ,"Paraburkholderia_bryophila"
         ,"Paraburkholderia_caffeinilytica"
         ,"Paraburkholderia_aspalathi"
         ,"Paraburkholderia_fungorum"
         ,"Paraburkholderia_graminis"
         ,"Paraburkholderia_caledonica"
         ,"Paraburkholderia_ginsengisoli"
         ,"Paraburkholderia_sartisoli"
         ,"Pseudomonas_acidophila"
         ,"Burkholderia_dabaoshanensis"
         ,"Robbsia_andropogonis"
         ,"Mycoavidus_cysteinexigens"
         ,"Ralstonia_solanacearum"
         ,"Ralstonia_mannitolilytica"
         ,"Ralstonia_insidiosa"
         ,"Ralstonia_pickettii"
         ,"Cupriavidus_gilardii"
         ,"Cupriavidus_basilensis"
         ,"Cupriavidus_plantarum"
         ,"Cupriavidus_pauculus"
         ,"Cupriavidus_metallidurans"
         ,"Cupriavidus_pinatubonensis"
         ,"Cupriavidus_alkaliphilus"
         ,"Cupriavidus_necator"
         ,"Cupriavidus_oxalaticus"
         ,"Enterobacillus_tribolii"
         ,"Buttiauxella_warmboldiae"
         ,"Buttiauxella_izardii"
         ,"Buttiauxella_agrestis"
         ,"Buttiauxella_ferragutiae"
         ,"Buttiauxella_gaviniae"
         ,"Buttiauxella_noackiae"
         ,"Buttiauxella_brennerae"
         ,"Cedecea_davisae"
         ,"Cedecea_lapagei"
         ,"Cedecea_neteri"
         ,"Atlantibacter_subterranea"
         ,"Atlantibacter_hermannii"
         ,"Pluralibacter_gergoviae"
         ,"Pseudescherichia_vulneris"
         ,"Raoultella_planticola"
         ,"Klebsiella_pneumoniae_subsp._pneumoniae"
         ,"Pyrinomonas_methylalipathogenes"
         ,"Terriglobus_roseus"
         ,"Bryocella_elongata"
         ,"Edaphobacter_dinghuensis"
         ,"Terracidiphilus_gabretensis"
         ,"Acidipila_dinghuensis"
         ,"Silvibacterium_bohemicum"
         ,"Acidobacterium_capsulatum"
         ,"Bryobacter_aggregatus")
nif <- c("Kosakonia_oryzae"
         ,"Kosakonia_arachidis"
         ,"Kosakonia_oryziphila"
         ,"Kosakonia_oryzendophytica"
         ,"Kosakonia_sacchari"
         ,"Mangrovibacter_plantisponsor"
         ,"Mangrovibacter_phragmitis"
         ,"Pseudomonas_oryzae"
         ,"Pseudomonas_linyingensis"
         ,"Pseudomonas_sagittaria"
         ,"Azotobacter_vinelandii"
         ,"Azotobacter_chroococcum"
         ,"Azotobacter_beijerinckii"
         ,"Pseudomonas_benzenivorans"
         ,"Pseudomonas_azotifigens"
         ,"Rhodomicrobium_udaipurense"
         ,"Ciceribacter_lividus"
         ,"Rhizobium_selenitireducens"
         ,"Prosthecomicrobium_hirschii"
         ,"Aquabacter_sp."
         ,"Azorhizobium_doebereinerae"
         ,"Xanthobacter_autotrophicus"
         ,"Xanthobacter_tagetidis"
         ,"Blastochloris_viridis"
         ,"Rhodoplanes_elegans"
         ,"Rhodoplanes_roseus"
         ,"Rhodoplanes_piscinae"
         ,"Rhodopseudomonas_pseudopalustris"
         ,"Rhodopseudomonas_palustris"
         ,"Rhodopseudomonas_thermotolerans"
         ,"Rhodopseudomonas_faecalis"
         ,"Bradyrhizobium_oligotrophicum"
         ,"Bradyrhizobium_mercantei"
         ,"Herbaspirillum_frisingense"
         ,"Herbaspirillum_seropedicae"
         ,"Herbaspirillum_rubrisubalbicans"
         ,"Burkholderia_vietnamiensis"
         ,"Paraburkholderia_kururiensis"
         ,"Paraburkholderia_caballeronis"
         ,"Paraburkholderia_ferrariae"
         ,"Paraburkholderia_tropica"
         ,"Paraburkholderia_bannensis"
         ,"Paraburkholderia_unamae"
         ,"Paraburkholderia_heleia"
         ,"Paraburkholderia_aromaticivorans"
         ,"Paraburkholderia_dilworthii"
         ,"Paraburkholderia_caryophylli"
         ,"Klebsiella_grimontii"
         ,"Klebsiella_michiganensis"
         ,"Klebsiella_variicola")
nod <- c("Rhizobium_pisi"
         ,"Rhizobium_anhuiense"
         ,"Rhizobium_leguminosarum_bv._phaseoli"
         ,"Rhizobium_leguminosarum_bv._trifolii"
         ,"Rhizobium_laguerreae"
         ,"Rhizobium_leguminosarum_bv._viciae"
         ,"Rhizobium_hidalgonense"
         ,"Rhizobium_acidisoli"
         ,"Rhizobium_aegyptiacum"
         ,"Rhizobium_bangladeshense"
         ,"Rhizobium_esperanzae"
         ,"Rhizobium_phaseoli"
         ,"Rhizobium_sophorae"
         ,"Rhizobium_mesoamericanum"
         ,"Rhizobium_altiplani"
         ,"Rhizobium_grahamii"
         ,"Rhizobium_tibeticum"
         ,"Rhizobium_sullae"
         ,"Rhizobium_etli"
         ,"Rhizobium_gallicum"
         ,"Rhizobium_jaguaris"
         ,"Rhizobium_lusitanum"
         ,"Rhizobium_freirei"
         ,"Rhizobium_tropici"
         ,"Rhizobium_undicola"
         ,"Neorhizobium_galegae"
         ,"Neorhizobium_huautlense"
         ,"Rhizobium_giardinii_bv._giardinii"
         ,"Sinorhizobium_americanum"
         ,"Ensifer_glycinis"
         ,"Sinorhizobium_fredii"
         ,"Ensifer_alkalisoli"
         ,"Ensifer_sojae"
         ,"Sinorhizobium_arboris"
         ,"Sinorhizobium_meliloti"
         ,"Sinorhizobium_medicae"
         ,"Ensifer_aridi"
         ,"Sinorhizobium_saheli"
         ,"Mesorhizobium_alhagi"
         ,"Mesorhizobium_tamadayense"
         ,"Mesorhizobium_hawassense"
         ,"Mesorhizobium_qingshengii"
         ,"Mesorhizobium_ciceri_biovar_biserrulae"
         ,"Mesorhizobium_sophorae"
         ,"Mesorhizobium_kowhaii"
         ,"Mesorhizobium_opportunistum"
         ,"Mesorhizobium_japonicum"
         ,"Mesorhizobium_huakuii"
         ,"Mesorhizobium_loti"
         ,"Mesorhizobium_erdmanii"
         ,"Mesorhizobium_australicum"
         ,"Mesorhizobium_waimense"
         ,"Mesorhizobium_amorphae"
         ,"Mesorhizobium_metallidurans"
         ,"Mesorhizobium_helmanticense"
         ,"Mesorhizobium_sanjuanii"
         ,"Mesorhizobium_mediterraneum"
         ,"Mesorhizobium_prunaredense"
         ,"Mesorhizobium_muleiense"
         ,"Mesorhizobium_wenxiniae"
         ,"Mesorhizobium_temperatum"
         ,"Methylobacterium_nodulans"
         ,"Microvirga_lotononidis"
         ,"Microvirga_vignae"
         ,"Azorhizobium_caulinodans"
         ,"Bradyrhizobium_canariense"
         ,"Bradyrhizobium_lablabi"
         ,"Bradyrhizobium_paxllaeri"
         ,"Bradyrhizobium_jicamae"
         ,"Bradyrhizobium_valentinum"
         ,"Bradyrhizobium_retamae"
         ,"Bradyrhizobium_icense"
         ,"Bradyrhizobium_neotropicale"
         ,"Bradyrhizobium_manausense"
         ,"Bradyrhizobium_arachidis"
         ,"Bradyrhizobium_diazoefficiens"
         ,"Bradyrhizobium_japonicum"
         ,"Bradyrhizobium_liaoningense"
         ,"Bradyrhizobium_yuanmingense"
         ,"Bradyrhizobium_ottawaense"
         ,"Bradyrhizobium_shewense"
         ,"Bradyrhizobium_elkanii"
         ,"Bradyrhizobium_embrapense"
         ,"Bradyrhizobium_tropiciagri"
         ,"Bradyrhizobium_viridifuturi"
         ,"Paraburkholderia_mimosarum"
         ,"Paraburkholderia_nodosa"
         ,"Paraburkholderia_diazotrophica"
         ,"Paraburkholderia_phymatum"
         ,"Paraburkholderia_sprentiae"
         ,"Paraburkholderia_tuberum"
         ,"Paraburkholderia_phenoliruptrix"
         ,"Paraburkholderia_rhynchosiae"
         ,"Paraburkholderia_terricola"
         ,"Paraburkholderia_ribeironis"
         ,"Paraburkholderia_symbiotica"
         ,"Cupriavidus_taiwanensis")
none <- gsub("_", " ", none)
nif <- gsub("_", " ", nif)
nod <- gsub("_", " ", nod)


